#!/bin/bash
# =============================================================================
# Script 5: Open Source Manifesto Generator
# Author: REET JAIN | Reg: 24BCE11435
# Course: Open Source Software | Slot: A24
# Description: Interactively asks the user 3 questions and generates a
#              personalised open-source philosophy statement, saved to a file.
#
# alias concept (demonstrated here — you can add this to ~/.bashrc):
# alias manifesto='bash ~/scripts/script5_manifesto_generator.sh'
# =============================================================================

# --- Output file name uses command substitution to get current username ---
OUTPUT="manifesto_$(whoami).txt"

# --- Get current date using the date command ---
DATE=$(date '+%d %B %Y')
TIME=$(date '+%H:%M:%S')

echo "============================================================"
echo "         OPEN SOURCE MANIFESTO GENERATOR                    "
echo "============================================================"
echo ""
echo "  Answer three questions to generate your personal"
echo "  open-source philosophy statement."
echo ""
echo "------------------------------------------------------------"

# --- Question 1: Interactive user input using read -p ---
read -p "  1. Name one open-source tool you use every day: " TOOL

# --- Question 2 ---
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM

# --- Question 3 ---
read -p "  3. Name one thing you would build and share freely: " BUILD

echo ""
echo "------------------------------------------------------------"
echo "  Generating your manifesto..."
echo "------------------------------------------------------------"
echo ""

# --- Compose the manifesto using string concatenation and write to file ---
# The { } block groups all echo statements and redirects output to the file at once
{
    echo "============================================================"
    echo "           MY OPEN SOURCE MANIFESTO"
    echo "============================================================"
    echo "  Generated by : $(whoami)"
    echo "  Date         : $DATE at $TIME"
    echo "  Student      : Devang Srivastava (24BCE10124)"
    echo "============================================================"
    echo ""
    echo "  Every day, I rely on $TOOL — a tool that strangers built"
    echo "  and shared freely, asking nothing in return. This simple"
    echo "  act of generosity has shaped the way I think about software"
    echo "  and about the world."
    echo ""
    echo "  To me, freedom means $FREEDOM. And I believe that freedom"
    echo "  is not something you keep to yourself — it multiplies when"
    echo "  you share it."
    echo ""
    echo "  So I commit: one day I will build $BUILD and release it"
    echo "  to the world under an open licence, so that others can"
    echo "  stand on my shoulders, just as I have stood on the"
    echo "  shoulders of those who came before me."
    echo ""
    echo "  Open source is not just a development model."
    echo "  It is a statement about what knowledge is for."
    echo ""
    echo "  Signed: $(whoami)"
    echo "  Date  : $DATE"
    echo "============================================================"
} > "$OUTPUT"   # Output redirection: write entire block to the file

# --- Display the generated manifesto ---
echo ""
cat "$OUTPUT"

echo ""
echo "------------------------------------------------------------"
echo "  [SAVED] Your manifesto has been saved to: $OUTPUT"
echo "------------------------------------------------------------"
echo ""
